#cloud-config
---
write_files:
  - path: /etc/kubelet-plugins/calico/calico_kubernetes.ini
    owner: root
    permissions: 0755
    content: |
      [config]
      # The Kubernetes master IP
      KUBERNETES_MASTER=172.18.18.101
      
      # IP and port of etcd instance used by Calico
      ETCD_AUTHORITY=172.18.18.101:2379
      
      # URL to access the Kubernetes apiserver
      KUBE_API_ROOT=https://172.18.18.101:8080/api/v1/

      DEFAULT_POLICY=none

      # Enable Calcio IPAM
      CALICO_IPAM=true

coreos:
  update:
    reboot-strategy: off
  units:
    - name: calico-node.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=calicoctl node
        After=docker.service ctls-install.service
        Requires=docker.service ctls-install.service
        
        [Service]
        User=root
        EnvironmentFile=/etc/network-environment
        Environment=ETCD_AUTHORITY=172.18.18.101:2379
        PermissionsStartOnly=true
        ExecStartPre=/usr/bin/wget -N -P /opt/bin http://www.projectcalico.org/builds/calicoctl
        ExecStartPre=/usr/bin/chmod +x /opt/bin/calicoctl
        ExecStart=/opt/bin/calicoctl node --kubernetes --kube-plugin-version=v0.7.0 --detach=false
        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target

    - name: kubelet.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/kubernetes/kubernetes
        After=calico-node.service
        Requires=calico-node.service

        [Service]
        EnvironmentFile=/etc/kubelet-plugins/calico/calico_kubernetes.ini
        ExecStartPre=/usr/bin/wget -N -P /opt/bin https://storage.googleapis.com/kubernetes-release/release/v1.1.2/bin/linux/amd64/kubelet
        ExecStartPre=/usr/bin/chmod +x /opt/bin/kubelet
        ExecStart=/opt/bin/kubelet \
        --port=10250 \
        --address=0.0.0.0 \
        --allow-privileged=true \
        --cluster-dns=10.100.0.10 \
        --cluster-domain=cluster.local \
        --api-servers=https://172.18.18.101:8080 \
        --network-plugin-dir=/etc/kubelet-plugins \
        --network-plugin=calico \
        --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
        --logtostderr=true
        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target
